name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/pull-request.yaml@main
    secrets: inherit

  scenario-tests:
    name: Scenario tests
    runs-on: ubuntu-latest
    needs:
      - lint
      - unit-test
      - static-checks
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install charmcraft
        run: snap install charmcraft
      - name: Fetch dependencies
        run: charmcraft fetch-lib charms.harness_extensions.v0.evt_sequences
      - name: Run scenario tests
        run: tox -vve scenario
